### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by IceKhan13** [Travis-S-IBM/q-kernel-ops#72]
Add license information to repository.

**Comment by Travis-S-IBM** [comment]
@IceKhan13 Please provide a recommendation (or requirement).


@mickahell Whatever is necessary to ensure compatibility with the requirements of packages in the Qiskit ecosystem.

**Comment by mickahell** [comment]
I propose the Apache one, its the same as for the Qiskit Ecosystem : https://github.com/qiskit-community/ecosystem/blob/main/LICENSE

**Comment by IceKhan13** [comment]
Apache 2 is great for open-source projects!

**Comment by mickahell** [comment]
Done : https://github.com/Travis-S-IBM/q-kernel-ops/blob/master/LICENCE
